matrix:
  include:
    - git:
        submodules: false
      language: python
      install:
        - pip install -r requirements.txt
        - pip install pytest-cov
      script:
        - python -m pytest
        - py.test --cov-report=xml --cov=contour_visualization tests/
    - git:
        submodules: false
      os: linux
      language: c++
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
        - git submodule update --init gtest
      script:
        - cd contour_visualization/cmodule
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ./tests/runBlendingOperatorsUnitTests
        - ./tests/runPictureMergeUnitTests