matrix:
  include:
    - git:
        submodules: false
      language: python
      install:
        - pip install -r requirements.txt
      script:
        - python -m pytest
    - git:
        submodules: false
      language: c++
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
      script:
        - cd contour_visualization/cmodule
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ./tests/runBlendingOperatorsUnitTests
        - ./tests/runBlendingOperatorsUnitTests
        - ctest